# scenario west of the californian coast to test reactive control

data_source_config: "cal_coast_Copernicus_hindcast_local"

folder_to_save: "scenario_flocking_no_hj_6days_no_curr_grad"

days_sim: 6

platforms_start:
  nb_platforms: 4
  lon: [-128.32, -128.25, -128.18, -128.10]
  lat: [32.75, 32.75, 32.75, 32.75]
  year: 2022
  month: 10
  day: 02
  hours: 12
  minutes: 0

target_region:
  lon: -128
  lat: 33
  radius: 0.12
  timeout_days: 2

multi_agent_param:
  network_graph_dict:
    unit: "km"
    communication_thrsld: &comm 9
    epsilon_margin: 1 # when dist > comm-plot_margin plot dashed red in animation
    collision_thrsld: 0.2

  hj_naive:
    unit: "km"
    communication_thrsld: *comm

  reactive_control: 
    type: "reactive_control"
    unit: "m"
    delta_3: 8800 # collision threshold (communication - delta_3)
    delta_2: 2000 # safe zone threshold  ]communication - delta_2, communication - delta_3[
    delta_1: 500 # small threshold so that if distance > communication_thrsld- delta_1 we try to achieve connectivity
    communication_thrsld: 9000
    k_1: 0.25
    k_2: 1

  flocking:
    epsilon: 0.1
    h: 0.2
    ideal_distance: 5000 # meters
    a: 5
    b: 5
    interaction_range: 9000 # meters

  initial_connections: Null