# Harder scenario in the gulf of mexico

data_source_config: "gulf_of_mexico_HYCOM_hindcast_local"

folder_to_save: "scenario_2_flocking_mergedMain"

days_sim: 2

platforms_start:
  nb_platforms: 4
  lon: [-83.2, -83.25, -83.3, -83.35]
  lat: [23.2, 23.25, 23.3, 23.35]
  year: 2021
  month: 11
  day: 24
  hours: 12
  minutes: 0

target_region:
  lon: -82.3
  lat: 24.35
  radius: 0.12
  timeout_days: 2

multi_agent_param:
  network_graph_dict:
    unit: "km"
    communication_thrsld: &comm 9
    epsilon_margin: 1 # when dist > comm-plot_margin plot dashed red in animation
    collision_thrsld: 0.2

  hj_naive:
    unit: "km"
    communication_thrsld: *comm

  reactive_control: 
    type: "reactive_control"
    unit: "m"
    mix_ttr_and_euclidean: True
    delta_3: 8800 # collision threshold (communication - delta_3)
    delta_2: 2000 # safe zone threshold  ]communication - delta_2, communication - delta_3[
    delta_1: 500 # small threshold so that if distance > communication_thrsld- delta_1 we try to achieve connectivity
    communication_thrsld: 9000
    k_1: 0.25
    k_2: 1

  flocking:
    unit: "km"
    epsilon: 10
    h: 0.2
    ideal_distance: 5 # km
    ideal_distance_low: 4.5 # km
    ideal_distance_high: 5.5 # km
    a: 5
    b: 5
    interaction_range: 9 # km
    hj_factor: 1
    grad_clip_range: 0.1 # km




  initial_connections: Null