# scenario west of the californian coast

data_source_config: "cal_coast_Copernicus_hindcast_local"

folder_to_save: "scenario_4"

days_sim: 3

platforms_start:
  nb_platforms: 4
  lon: [-126, -126.3, -125.85, -125.75]
  lat: [33.3, 33.6, 33.7, 33.5]
  year: 2022
  month: 10
  day: 02
  hours: 12
  minutes: 0

target_region:
  lon: -126
  lat: 33
  radius: 0.12
  timeout_days: 2

multi_agent_param:
  network_graph_dict:
    unit: "km"
    communication_thrsld: 9
    margin: 1
    collision_thrsld: 1

  initial_connections: Null