experiment_runner:
  metrics:
    - "rmse"
    - "r2"
    - "vme"
    - "ratio_per_tile"
    #- "vector_correlation"
  direction_current: [ "uv" ]# , "u", "v" ]

  #number_burnin_steps: 50
  number_burnin_steps: 0
  number_steps_prediction: 96
  delta_between_predictions_in_sec: 3600 #1h
  time_horizon_predictions_in_sec: 86400 # 24 *3600
  radius_area_around_platform: 1 # 0.25
  number_steps_to_predict: 12
  gt_additional_area: 0.1
  gt_additional_time: 3600

  use_real_data: True
  #scenario_used: "gm_GP_025_12"
  scenario_used: "gm_GP_05_24"
  folder_scenario: "./ablation_study/configs_GP"

observer:
  life_span_observations_in_sec: 100000

  model:
    NN:
      dimension_input: [ 12,13,13 ]
      model_error: false
      type: 'cnn'
      parameters:
        path_weights: "ablation_study/CNN_models_saved/medium_tile_big_ds.h5"

        ch_sz: [ 6,24,48,96,192 ]
        downsizing_method: "avgpool"
        dropout_encoder: 0.24299222476871712
        dropout_decoder: 0.13587898683659105
        dropout_bottom: 0.7479602916555403
        initial_channels: [ 0,1,2,3,6,7 ]
        output_paddings: [ [ 0,1,1 ],[ 1,0,0 ],[ 1,0,0 ] ]
    gaussian_process:
      kernel:
        type: 'matern'
        sigma_exp_squared: 5.011571057964094
        scaling:
          latitude: 0.5753005356364821
          longitude: 0.5967749664273109
          time: 42103.57591355196
        parameters:
          length_scale_bounds: "fixed"
          nu: 1.5
