#simulator_config:
dt: 8064.0             # in seconds
conv_m_to_deg: 111120.    # used to transform anything in meters to in degrees (assuming sphere)
int_pol_type: 'linear'   # either bspline or linear (linear is faster as the dynamics don't need to be fit a priori)
sim_integration: 'ef'     # either 'rk' (a 4th order method) or forward euler 'ef'