version: "3.7"
services:
  jupyterlab-server:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ../:ocean_platform
    init: true
    stdin_open: true
    tty: true