model: "unet"
wandb_mode: "offline"
save_base_path: "data/drifter_data/models"

unet:
  in_channels: 2
  out_channels: 2
  features: [64, 128, 256, 512]
  dropout: False

train:
  learning_rate: 1e-4
  batch_size: 1
  test_batch_size: 2
  epochs: 100
#  loss_type: "sparse_mse"
#  loss_type: "sparse_mse_and_tv"
  loss_type: "mse"
  dataset_fraction: 1

optimizer:
  name: "Adam"
  parameters:
    betas: [0.95, 0.9995]
    eps: 0.00001
    weight_decay: 0.0003

dataset:
  type: "ForecastDataset"
  forecasts: "data/drifter_data/forecasts/area1"
  ground_truth: "data/drifter_data/dataset_forecast_error/area1"
  sparse_type: "forecast"
  shuffle: False
  len: 1

