model: "generator"
dataset_type: "forecastbuoy"
wandb_mode: "offline"
save_base_path: "data/drifter_data/models"
metrics: ["rmse", "vector_correlation"]
run_train: False

load_from_chkpt:
  value: False
  file_name: "2022-11-21_17:51:56.pth"

# testing and saving output
save_samples_path: "data/drifter_data/Gen_samples"
save_repeated_samples_path: "data/drifter_data/Gen_samples_repeated"

generator:
  in_channels: 2
  out_channels: 2
  features: 64
  dropout: True
  dropout_all: False
  dropout_val: 0.3
  init_type: "xavier"
  init_gain: 1.0
  norm_type: "batch"

train:
  batch_size: 32
  test_batch_size: 192
  epochs: 30
  loss:
    # choice: l1, mse, sparse_mse, total_variation, mass_conservation
    types: [ "l1" ]
    weighting: [ 1 ]
  learning_rate: 0.0001
  lr_scheduler_configs:
    value: True
    scheduler_type: "plateau"
    mode: "min"
    factor: 0.2
    threshold: 0.0001
    patience: 3

optimizer:
  name: "Adam"
  parameters:
#    betas: [0.95, 0.9995]
    betas: [0.5, 0.999]
    eps: 0.00001
    weight_decay: 0.0003

dataset:
  forecasts: "data/drifter_data/forecasts_preprocessed"
  hindcasts: "data/drifter_data/hindcasts_preprocessed"
  ground_truth: "data/drifter_data/buoy_preprocessed"
  area: ["area1"]
  shuffle: True
  len: None
  split: [0.8, 0.2]
  concat_len: 1

val_dataset:
  forecasts: "data/drifter_data/forecasts_preprocessed_val"
  ground_truth: "data/drifter_data/buoy_preprocessed_val"
  area: ["area1"]
  concat_len: 1

test_dataset:
  forecasts: "data/drifter_data/forecasts_preprocessed_test"
  ground_truth: "data/drifter_data/buoy_preprocessed_test"
#  forecasts: "data/drifter_data/thesis_gan_inference/forecast/"
#  ground_truth: "data/drifter_data/thesis_gan_inference/ground_truth"
  area: ["area1"]
  concat_len: 1