model: ["generator", "discriminator"]
save_model: False
dataset_type: "forecastbuoy"
wandb_mode: "offline"
save_base_path: "data/drifter_data/models"
metrics: ["rmse", "vector_correlation"]

# testing and saving output
save_samples_path: "data/drifter_data/GAN_samples_repeated"
#test_load_chkpt: "2022-11-27_22:48:44.pth"
test_load_chkpt: "2022-12-10_13:09:12.pth"

generator:
  in_channels: 2
  out_channels: 2
  features: 64
  dropout: True
  dropout_all: False
  dropout_val: 0.3
  init_type: "xavier"
  init_gain: 1.0
  norm_type: "instance"
  load_from_chkpt: True
  chkpt: "2022-11-17_17:59:56.pth"
  freeze_encoder: True
  init_decoder: True

gen_optimizer:
  name: "Adam"
  parameters:
#    betas: [0.95, 0.9995]
    betas: [0.5, 0.999]
    eps: 0.00001
    weight_decay: 0.0003

discriminator:
  in_channels: 2
  features: [64, 128, 256, 512]
  init_type: "xavier"
  init_gain: 1.0
  norm_type: "batch"
  load_from_chkpt: False
  chkpt: ""

disc_optimizer:
  name: "Adam"
  parameters:
#    betas: [0.95, 0.9995]
    betas: [0.5, 0.999]
    eps: 0.00001
    weight_decay: 0.0003

train:
  batch_size: 32
  test_batch_size: 192
  epochs: 30
  loss:
    gen: [ "gan_gen", "l1"]
    gen_weighting: [ 1, 100 ]
    disc: [ "gan_disc" ]
    disc_weighting: [ 1 ]
  learning_rate: 0.0001
  lr_scheduler_configs:
    value: True
    scheduler_type: "plateau"
    mode: "min"
    factor: 0.2
    threshold: 0.0001
    patience: 3

dataset:
  forecasts: "data/drifter_data/forecasts_preprocessed"
  hindcasts: "data/drifter_data/hindcasts_preprocessed"
  ground_truth: "data/drifter_data/buoy_preprocessed"
  area: ["area1"]
  shuffle: True
  len: None
  split: [0.9, 0.1]
  concat_len: 1

test_dataset:
#  forecasts: "data/drifter_data/forecasts_preprocessed_test"
#  ground_truth: "data/drifter_data/buoy_preprocessed_test"
  forecasts: "data/drifter_data/GAN_repeated_test/forecasts"
  ground_truth: "data/drifter_data/GAN_repeated_test/buoy"
#  forecasts: "data/drifter_data/thesis_gan_inference/forecast/"
#  ground_truth: "data/drifter_data/thesis_gan_inference/ground_truth"
  area: ["area1"]
  concat_len: 1

