data_dir: "data/drifter_data/"
dataset_type: "forecast"

experiment_runner:
  metrics:
    - "rmse"
  dataset: "area1"
#  problems_file: "./scenarios/generative_error_model/problems.yaml"
  problems:
    - data_ranges:
        lon_range: [-140, -120]
        lat_range: [20, 30]
        t_range: "2022-04-21T12:30:00Z/2022-04-30T12:30:00Z" # in ISO8601 format

model:
  type: "simplex_noise"
  simplex_noise:
    area1: "variogram_params/tuned_2d_forecast_variogram_area1_[5.0, 1.0]_False_True.npy"
#    area1: "variogram_params/tuned_2d_hindcast_area1_True_True.npy"
  gan: "space holder"

dataset_writer:
  source: "copernicus"
  dataset_type: "forecast"
  input: "area1"
  output: "area1"

buoy_config:
  copernicus:
    dataset:
      # drifter
      download_index_files: False
      host: "nrt.cmems-du.eu"
      product: "INSITU_GLO_UV_NRT_OBSERVATIONS_013_048"
      name: "drifter"
      index_files: ["index_latest.txt", "index_monthly.txt", "index_history.txt"]
      index_platform: "index_platform.txt"
      # # argo
      # host: "nrt.cmems-du.eu"
      # product: "INSITU_GLO_UV_NRT_OBSERVATIONS_013_048"
      # name: "argo"
      # index_files: ["index_latest.txt"]
    area_overlap_type: "intersects"
    lon_range: [ -140, -120 ]
    lat_range: [ 20, 30 ]
    time_range: "2022-04-21T12:30:00Z/2022-04-30T12:30:00Z"
    usr: "jdieker"
    pas: "AxxzVqCuC#!vS69"
  sofar:
    data_dir: ""
    time_range: ""
    lat_range: [0,0]
    lon_range: [0,0]

copernicus_opendap:
  hindcast:
    field: "OceanCurrents"
    source: "opendap"
    source_settings:
      service: "copernicus"
      currents: "total"
      USERNAME: "jdieker"
      PASSWORD: "AxxzVqCuC#!vS69"
      DATASET_ID: "cmems_mod_glo_phy_anfc_merged-uv_PT1H-i"
  forecast: null

local_forecast:
  field: "OceanCurrents"
  source: "forecast_files"
  source_settings:
    folder: ""     # set at runtime
    currents: "total"

sim_cache_dict:
  deg_arount_x_t: 1
  time_around_x_t: 86400
