model: "generator"
dataset_type: "forecasthindcast"
wandb_mode: "online"
save_base_path: "data/drifter_data/models"
save_samples_path: "data/drifter_data/GAN_samples"
metrics: ["rmse", "vector_correlation"]
run_train: True

load_from_chkpt:
  value: False
  file_name: "2022-11-17_17:59:56.pth"

generator:
  in_channels: 2
  out_channels: 2
  features: 64
  dropout: False
  dropout_all: True
  dropout_val: 0.3
  init_type: "xavier"
  init_gain: 1.0
  norm_type: "instance"

train:
  batch_size: 32
  test_batch_size: 32
  epochs: 30
  loss:
    # choice: l1, mse, sparse_mse, total_variation, mass_conservation
    types: [ "l1" ]
    weighting: [ 1 ]
  learning_rate: 0.0001
  lr_scheduler_configs:
    value: True
    scheduler_type: "plateau"
    mode: "min"
    factor: 0.2
    threshold: 0.0001
    patience: 3

optimizer:
  name: "Adam"
  parameters:
#    betas: [0.95, 0.9995]
    betas: [0.5, 0.999]
    eps: 0.00001
    weight_decay: 0.0003

dataset:
  forecasts: "data/drifter_data/forecasts_preprocessed"
  hindcasts: "data/drifter_data/hindcasts_preprocessed"
  ground_truth: "data/drifter_data/dataset_forecast_error/area1"
  sparse_type: "forecast"
  area: ["area1"]
  shuffle: True
  len: None
  split: [0.95, 0.025, 0.025]
  random_subsets: False  # if len < len(dataset) how to choose subsets?
  concat_len: 1
