experiment_runner:
  metrics:
    - "rmse"
  dataset: "area1"
#  problems_file: "./scenarios/generative_error_model/problems.yaml"
  problems:
    - data_ranges:
#        lon_range: [-140, -120]
#        lat_range: [20, 30]
        lon_range: [-140, -135]
        lat_range: [20,25]
        t_range: "2022-04-24T13:00:00Z/2022-05-03T13:00:00Z" # in ISO8601 format

model:
  type: "simplex_noise"
  simplex_noise:
    area1:
      U_COMP: [[0.5, 702.5, 1407.3, 245.0], [0.5, 302.5, 1207.3, 187.0]]
      V_COMP: [[0.5, 702.5, 1407.3, 245.0], [0.5, 302.5, 1207.3, 187.0]]

  gan: "space holder"

buoy_config:
  copernicus:
    data_dir: "/home/jonas/Documents/Thesis/OceanPlatformControl/data"
    dataset:
      # drifter
      download_index_files: False
      host: "nrt.cmems-du.eu"
      product: "INSITU_GLO_UV_NRT_OBSERVATIONS_013_048"
      name: "drifter"
      index_files: ["index_latest.txt", "index_monthly.txt", "index_history.txt"]
      index_platform: "index_platform.txt"
      # # argo
      # host: "nrt.cmems-du.eu"
      # product: "INSITU_GLO_UV_NRT_OBSERVATIONS_013_048"
      # name: "argo"
      # index_files: ["index_latest.txt"]
    time_range: "2022-04-24T13:00:00Z/2022-05-03T13:00:00Z" # in ISO8601 format
    # lat_range: [-40, -20]
    # lon_range: [-120, -100]
    lat_range: [25.0, 30.0]
    lon_range: [-140, -120]
    area_overlap_type: "intersects"
    usr: "jdieker"
    pas: "AxxzVqCuC#!vS69"
  sofar:
    data_dir: ""
    time_range: ""
    lat_range: [0,0]
    lon_range: [0,0]

copernicus_opendap:
  hindcast:
    field: "OceanCurrents"
    source: "opendap"
    source_settings:
      service: "copernicus"
      currents: "total"
      USERNAME: "jdieker"
      PASSWORD: "AxxzVqCuC#!vS69"
      DATASET_ID: "cmems_mod_glo_phy_anfc_merged-uv_PT1H-i"
  forecast: null

local_forecast:
  field: "OceanCurrents"
  source: "forecast_files"
  source_settings:
    folder: "/home/jonas/Documents/Thesis/OceanPlatformControl/data/drifter_data/forecasts/area1/"

sim_cache_dict:
  deg_arount_x_t: 1
  time_around_x_t: 86400

data_dir: "/home/jonas/Documents/Thesis/OceanPlatformControl/data/drifter_data/"
