observer:
  life_span_observations_in_sec: 86400

  model:
    NN:
      NN_radius_space: 1 # this should be the same it is trained on!
      NN_lags_in_second: 43200 # this should be the same it is trained on!
      dimension_input: [ 12,25,25 ]
      model_error: false
      type: 'cnn'
      parameters:
        path_weights: "package_data/big_tile_big_ds.h5"
        ch_sz: [ 6,32,64,64,128 ]
        downsizing_method: "avgpool"
        dropout_encoder: 0.35044302687330947
        dropout_decoder: 0.3940046389660926
        dropout_bottom: 0.5316670044828303
        initial_channels: [ 0,1,2,3,6,7 ]
        activation: "elu"
        output_paddings: [ [ 0,0,0 ],[ 1,0,0 ],[ 1,0,0 ] ]
    gaussian_process:
      kernel:
        type: 'matern'
        sigma_exp_squared: 5.011571057964094
        scaling:
          latitude: 0.5753005356364821
          longitude: 0.5967749664273109
          time: 42103.57591355196
        parameters:
          length_scale_bounds: "fixed"
          nu: 1.5