experiment_runner:
  #  plots:
  #    visualize_currents: True
  #    plot_3d:
  #      [ "error" ] #, "std_error", "initial_forecast", "water", "ground_truth" ]
  #    visualize_metrics: True
  metrics:
    - "rmse"
    - "r2"
    - "vme"
    #- "vector_correlation"
  direction_current: [ "uv" , "u", "v" ]

  #number_burnin_steps: 50
  number_burnin_steps: 0
  number_steps_prediction: 2 #96 #120
  delta_between_predictions_in_sec: 3600 #1h
  time_horizon_predictions_in_sec: 86400 # 24 *3600
  radius_area_around_platform: 0.9 #0.04665226 #3.89189189
  number_steps_to_predict: 12
  gt_additional_area: 0.12
  gt_additional_time: 3600
  clear_observations_when_new_file: True

  use_real_data: True
  scenario_used: "gulf_of_mexico_files_april_june_july_august"
  #problems_file: "./scenarios/ocean_observer/all_problems.yaml"
#  problems:
#    - initial_position:
#        lon_in_deg: -86
#        lat_in_deg: 24.86
#        datetime: "2021-11-22T12:00:00Z" #In iso8601 format!
#      target:
#        lon_in_deg: -88.61
#        lat_in_deg: 26.36
#        radius_in_m: 1
#    - initial_position:
#        lon_in_deg: -82
#        lat_in_deg: 24.86
#        datetime: "2021-11-23T12:00:00Z" #In iso8601 format!
#      target:
#        lon_in_deg: -84.61
#        lat_in_deg: 26.36
#        radius_in_m: 1

observer:
  life_span_observations_in_sec: 43200 # 12 * 3600

  model:

    # After bug :
    gaussian_process:
      kernel:
        type: 'matern'
        sigma_exp_squared: 3.4904
        scaling:
          latitude: 0.48426081
          longitude: 0.6580229922
          time: 31553.8074593
        parameters:
          length_scale_bounds: "fixed"
          nu: 1.5
