platform_config:
    battery_cap: 700        # in Wh
    u_max: 0.1              # in m/s we think will be in range 0.05 - 0.2 m/s
#    motor_power: 1.0       # in Watt => this info is implicit in u_max
    motor_efficiency: 0.5    # how much of the energy used from the motor is force for the platform
    drag_factor: 675        # all except the u^3 of power needed to overcome drag: 0.5*rho*C_d*A
    solar_panel_size: .5    # size of solar panel in m^2
    solar_efficiency: 0.2   # fraction of incoming solar radiation transformed to electricity