platform_config:
    battery_cap: 20.0       # in Wh
    u_max: .1               # in m/s we think will be in range 0.05 - 0.2 m/s
#    motor_power: 1.0       # in Watt => this info is implicit in u_max
    motor_efficiency: 1.    # how much of the energy used from the motor is force for the platform
    avg_solar_power: 10.   # in Watt NOTE: not yet accounting for day-night difference!
    drag_factor: 10.       # all except the v^3 of power needed to overcome drag: 0.5*rho*C_d*A
