---
arguments_model_runner:
  yaml_file_datasets: "config_neural_net"
  batch_size: 128
  validation_batch_size: 1000
  model_type: "cnn"
  log_interval: 1
  lr: 0.0001 #0.0003
  epochs: 200
  folder_figure: "./figures/"
  max_batches_training_set: 2000
  max_batches_validation_set: 500
  optimizer:
    name: "Adam"
    parameters:
      betas: [ 0.95, 0.9995 ]
      eps: 0.000001
      weight_decay: 0.0003 #0.0010 #0.005 # instead of 0.02 #0.15
  scheduler:
    name: "ReduceLROnPlateau"
    parameters:
      mode: 'min'
      factor: 0.2
      patience: 7
      threshold: 0.005
arguments_script_convert_data:
  yaml_file_datasets: "config_neural_net"
model:
  cfg_neural_network:
    ch_sz: [ 2, 32, 64, 128, 192 ]
    activation: "relu"
    downsizing_method: "conv"
    dropout_encoder: 0.1
    dropout_bottom: 0.4
    dropout_decoder: 0.3
  cfg_dataset:
    radius_lon: 0.25
    radius_lat: 0.25
    margin_forecast: 0.1
    stride_tiles_dataset: 0.5
    time_horizon_input_h: 12
    time_horizon_output_h: 12
    stride_time_dataset_h: 6
    input_shape:
      - 2
      - 12
      - 7
      - 7
    output_shape:
      - 2
      - 12
      - 7
      - 7
    index_axis_time: 2
  model_error: false
data_generation:
  parameters_input:
    start_training: '2022-05-03T12:30:01Z'
    duration_training_in_h: 720 #24 * 30
    start_validation: '2022-08-25T12:30:01Z'
    duration_validation_in_h: 504 # 21 * 24
    input_tile_dims: [ 7, 7, 12 ]
    window_shift: 0 # if window shift = 2: input: [x{t-2} .. x{t+2}]
    # if window shift = 0: input= [x{t}...x{t+4}]
    output_tile_dims: [ 7, 7, 12 ]
    size_per_file_in_mb: 2000
    folder_training: "./data_ablation_study/training_small_ds_CNN_small_tile/"
    shuffle_training: True
    #folder_validation: "./data_NN/data_validation_30_days_without_nan/"
    folder_validation: "./data_ablation_study/validation_small_ds_CNN_small_tile/"
    shuffle_validation: False

config_neural_net:
  training:
    hindcast:
      field: 'OceanCurrents'
      source: 'hindcast_files'
      source_settings:
        #'folder': "data/single_day_hindcasts/" #21/11/2021 -> 12/12/2021#"data/hindcast_test/"
        #'folder': 'data/single_day_hindcasts/' # 21/11 -> 27/11 + 22/12 -> 27/12
        #'folder': 'data/april_may_data/hindcast_HYCOM_all_one_file_april/'
        'folder':
          - 'data_ablation_study/hc/april/'
          - 'data_ablation_study/hc/may/'
          - 'data_ablation_study/hc/june/'
          - 'data_ablation_study/hc/july/'
          - 'data_ablation_study/hc/august/'
          - 'data_ablation_study/hc/september/'
      #'folder': 'data/hindcast_HYCOM_all_one_file_april/'
    forecast:
      field: 'OceanCurrents'
      source: 'forecast_files'
      source_settings:
        #'folder': "data/forecast_test/"# "data/cop_fmrc/" # 21/11/2021 -> 06/12/2021
        #'folder': "data/unique_forecast_test/" # 22/11/2021 -> 28/11/2021
        'folder':
          - 'data_ablation_study/fc/april/'
          - 'data_ablation_study/fc/may/'
          - 'data_ablation_study/fc/june/'
          - 'data_ablation_study/fc/july/'
          - 'data_ablation_study/fc/august/'
          - 'data_ablation_study/fc/september/'
        #'folder': 'data/april_may_data/forecasts_HYCOM_april_8th_to_june_6th/'
        'currents': 'total'
  validation:
    hindcast:
      field: 'OceanCurrents'
      source: 'hindcast_files'
      source_settings:
        #'folder': "data/single_day_hindcasts/" #21/11/2021 -> 12/12/2021#"data/hindcast_test/"
        #'folder': 'data/single_day_hindcasts/' # 21/11 -> 27/11 + 22/12 -> 27/12
        #'folder': 'data/april_may_data/hindcast_HYCOM_all_one_file_april/'
        'folder':
          #          - 'data_ablation_study/hc/april/'
          #- 'data_ablation_study/hc/may/'
          #          - 'data_ablation_study/hc/june/'
          #          - 'data_ablation_study/hc/july/'
          - 'data_ablation_study/hc/august/'
          - 'data_ablation_study/hc/september/'
      #'folder': 'data/hindcast_HYCOM_all_one_file_april/'
    forecast:
      field: 'OceanCurrents'
      source: 'forecast_files'
      source_settings:
        #'folder': "data/forecast_test/"# "data/cop_fmrc/" # 21/11/2021 -> 06/12/2021
        #'folder': "data/unique_forecast_test/" # 22/11/2021 -> 28/11/2021
        'folder':
          #          - 'data_ablation_study/fc/april/'
          # - 'data_ablation_study/fc/may/'
          #          - 'data_ablation_study/fc/june/'
          #          - 'data_ablation_study/fc/july/'
          - 'data_ablation_study/fc/august/'
          - 'data_ablation_study/fc/september/'
        'currents': 'total'