# Ray Cluster Launcher Configuration
# Documentation: https://docs.ray.io/en/latest/cluster/cloud.html#
# Example: https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/azure/example-full.yaml
# Defaults: https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/azure/defaults.yaml


# An unique identifier for the head node and workers of this cluster.
cluster_name: default

# The maximum number of workers nodes to launch in addition to the head node.
initial_workers: 5
min_workers: 5
max_workers: 5

# Cloud-provider specific configuration.
provider:
    type: azure
    # https://azure.microsoft.com/en-us/global-infrastructure/locations
    location: eastus
    resource_group: jerome-ray-cluster-launcher
    # set subscription id otherwise the default from az cli will be used
    subscription_id: 320d211e-ea73-4cc2-9f71-18da686ab665
    cache_stopped_nodes: True

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu
    # you must specify paths to matching private and public key pair files
    # use `ssh-keygen -t rsa -b 4096` to generate a new ssh key pair
    ssh_private_key: ~/.ssh/azure
    # changes to this should match what is specified in file_mounts
    ssh_public_key: ~/.ssh/azure.pub

# Tell the autoscaler the allowed node types and the resources they provide.
# The key is the name of the node type, which is just for debugging purposes.
# The node config specifies the launch config and physical instance type.
available_node_types:
    ray.head.default:
        max_workers: 0
        # The resources provided by this node type.
        resources: {"CPU": 6, "GPU": 1}
        # Provider-specific config, e.g. instance type.
        node_config:
            azure_arm_parameters:
                # Popular Sizes:
                #   - Standard_NC6_Promo (US$289.08)
                #   - Standard_NC12_Promo (US$578.16)
                #   - Standard_NC24_Promo (US$1,156.32)
                #   -- Standard_D2s_v3 (US$70.08)
                #   -- Standard_D4s_v3 (US$140.16)
                #   -- Standard_D8s_v3 (US$280.32)
                #   -- Standard_D16s_v3 (US$560.64)
                #   -- Standard_D32s_v3 (US$1,121.28)
                #   -- Standard_D64s_v3 (US$2,242.56)
                #   --- Standard_F32s_v2 (US$987.69)
                # Costs Example:
                # - 1 * Standard_NC6_Promo + 8 * Standard_D4s_v3 = 289 + 6 * 140 = 1129$/month = 37$/day = 1.6$/hour
                # - 8 * Standard_NC6_Promo = 8 * 289 = 2312$/month = 77$/day = 3.2$/hour
                vmSize: Standard_NC6_Promo
                # List images https://docs.microsoft.com/en-us/azure/virtual-machines/linux/cli-ps-findimage
                imagePublisher: microsoft-dsvm
                imageOffer: ubuntu-2004
                imageSku: '2004'
                imageVersion: latest

    ray.worker.default:
        # The minimum number of worker nodes of this type to launch.
        # This number should be >= 0.
        min_workers: 5
        # The maximum number of worker nodes of this type to launch.
        # This takes precedence over min_workers.
        max_workers: 5
        # The resources provided by this node type.
        resources: {"CPU": 6, "GPU": 1}
        # Provider-specific config, e.g. instance type.
        node_config:
            azure_arm_parameters:
                vmSize: Standard_NC6_Promo
                # List images https://docs.microsoft.com/en-us/azure/virtual-machines/linux/cli-ps-findimage
                imagePublisher: microsoft-dsvm
                imageOffer: ubuntu-2004
                imageSku: '2004'
                imageVersion: latest
                # optionally set priority to use Spot instances
                # priority: Spot
                # set a maximum price for spot instances if desired
                # billingProfile:
                #     maxPrice: -1

# Specify the node type of the head node (as configured above).
head_node_type: ray.head.default

# Files or directories to copy to the head and worker nodes. The format is a
# dictionary from REMOTE_PATH: LOCAL_PATH, e.g.
file_mounts: {
    "~/.ssh/azure.pub": "~/.ssh/azure.pub",
    "~/setup": "setup",
}

# Files or directories to copy from the head node to the worker nodes. The format is a
# list of paths. The same path on the head node will be copied to the worker node.
# This behavior is a subset of the file_mounts behavior. In the vast majority of cases
# you should just use file_mounts. Only use this if you know what you're doing!
cluster_synced_files: []

# Whether changes to directories in file_mounts or cluster_synced_files in the head node
# should sync to the worker node continuously
file_mounts_sync_continuously: False

# Patterns for files to exclude when running rsync up or rsync down
rsync_exclude:
    - "**/.git"
    - "**/.git/**"

# Pattern files to use for filtering out files when running rsync up or rsync down. The file is searched for
# in the source directory and recursively through all subdirectories. For example, if .gitignore is provided
# as a value, the behavior will match git's behavior for finding and using .gitignore files.
rsync_filter:
    - ".gitignore"

# List of commands that will be run before `setup_commands`. If docker is
# enabled, these commands will run outside the container and before docker
# is setup.
initialization_commands:
    # get rid of annoying Ubuntu message
    - touch ~/.sudo_as_admin_successful

# List of shell commands to run to set up nodes.
# NOTE: rayproject/ray-ml:latest has ray latest bundled
setup_commands:
    # Note: if you're developing Ray, you probably want to create an AMI that
    # has your Ray repo pre-cloned. Then, you can replace the pip installs
    # below with a git checkout <your_sha> (and possibly a recompile).
    # - (which conda && echo 'eval "$(conda shell.bash hook)"' >> ~/.bashrc) || true
    # - (conda activate py38_pytorch &> /dev/null && echo 'conda activate py38_pytorch' >> ~/.bashrc) || true
    # - (conda activate py38_tensorflow &> /dev/null && echo 'conda activate py38_tensorflow' >> ~/.bashrc) || true
    # - which ray || pip install -U "ray[default] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl"
    # Consider uncommenting these if you also want to run apt-get commands during setup
    # - sudo pkill -9 apt-get || true
    # - sudo pkill -9 dpkg || true
    # - sudo dpkg --configure -a
    - (which conda && echo 'eval "$(conda shell.bash hook)"' >> ~/.bashrc) || true
    - bash -i ~/setup/set_up_ocean_platform_env.sh
    - (conda activate ocean_platform &> /dev/null && echo 'conda activate ocean_platform' >> ~/.bashrc) || true
    - export PYTHONPATH="${PYTHONPATH}:/home/ubuntu"

# Custom commands that will be run on the head node after common setup.
head_setup_commands:
    - pip install -U azure-cli-core azure-identity azure-mgmt-compute azure-mgmt-network azure-mgmt-resource msrestazure

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop --force
    - ulimit -n 65536; ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop --force
    - ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076

head_node: {}
worker_nodes: {}