casadi_cache_dict:
    deg_around_x_t: 10.0
    time_around_x_t: 1000.0

platform_dict:
    battery_cap_in_wh: 400.0
    u_max_in_mps: 0.1
    motor_efficiency: 1.0
    solar_panel_size: 0.5
    solar_efficiency: 0.2
    drag_factor: 675.0
    dt_in_s: 1

use_geographic_coordinate_system: False

spatial_boundary:
    x: [0, 10]
    y: [0, 10]

timeout: 100 # Time Units

ocean_dict:
    hindcast:
        field: 'OceanCurrents'
        source: 'analytical'
        source_settings:
            name: 'FixedCurrentHighway'
            boundary_buffers: [0.2, 0.2]
            x_domain: [0, 10]
            y_domain: [0, 10]
            temporal_domain: [0, 1000]
            spatial_resolution: 0.1
            temporal_resolution: 10
            y_range_highway: [4.5, 5.5]
            U_cur: 0.2
    forecast: null

solar_dict: null

seaweed_dict: null

platform_state:
    lon: 0
    lat: 0
    date_time: 1970-01-01 00:00:00Z
    battery_charge: 0
    seaweed_mass: 0

end_region:
    lon: 10
    lat: 10