casadi_cache_dict:
    deg_around_x_t: 1.5
    time_around_x_t: 432000. # 3600 * 24 * 5

platform_dict:
    battery_cap_in_wh: 400.0
    u_max_in_mps: 0.1
    motor_efficiency: 1.0
    solar_panel_size: 0.5
    solar_efficiency: 0.2
    drag_factor: 675.0
    dt_in_s: 3600.0

use_geographic_coordinate_system: True

spatial_boundary: null

ocean_dict:
    hindcast:
        field: 'OceanCurrents'
        source: 'opendap'
        source_settings:
            service: 'copernicus'
            currents: 'total'
            USERNAME: 'mmariuswiggert'
            PASSWORD: 'tamku3-qetroR-guwneq'
            DATASET_ID: 'cmems_mod_glo_phy_anfc_merged-uv_PT1H-i'
    forecast:
        null

solar_dict:
    hindcast: null
    forecast: null

seaweed_dict:
    hindcast: null
    forecast: null