casadi_cache_dict:
    deg_around_x_t: 0.5
    time_around_x_t: 172800. # 3600 * 24 * 5

platform_dict:
    battery_cap_in_wh: 400.0
    u_max_in_mps: 0.1
    motor_efficiency: 1.0
    solar_panel_size: 0.5
    solar_efficiency: 0.2
    drag_factor: 675.0
    dt_in_s: 600.0

use_geographic_coordinate_system: True

spatial_boundary: null

ocean_dict:
    hindcast:
        field: 'OceanCurrents'
        source: 'hindcast_files'
        source_settings:
            folder: "/Users/matthiaskiller/Desktop/data/Copernicus/Hindcast/Region 3/"
            source: "HYCOM"
            type: "hindcast"
   
    forecast:
        field: 'OceanCurrents'
        source: 'longterm_average'
        source_settings:
          forecast:
            field: 'OceanCurrents'
            source: 'forecast_files'
            source_settings:
              folder: "/Users/matthiaskiller/Desktop/data/HYCOM/Forecast/Region 3/"
          average:
            field: 'OceanCurrents'
            source: 'hindcast_files'
            source_settings:
              folder: "/Users/matthiaskiller/Desktop/data/Copernicus/Averages_monthly/"
              currents: 'normal'

solar_dict:
    hindcast: null
    forecast: null

seaweed_dict:
    hindcast: null
    forecast: null