casadi_cache_dict:
    deg_around_x_t: 0.5
    time_around_x_t: 36000. # 3600 * 24 * 5

platform_dict:
    battery_cap_in_wh: 400.0
    u_max_in_mps: 0.1
    motor_efficiency: 1.0
    solar_panel_size: 0.5
    solar_efficiency: 0.2
    drag_factor: 675.0
    dt_in_s: 1800.0

use_geographic_coordinate_system: True

spatial_boundary: null
timeout: 432000 #120h

ocean_dict:
    region: "GOM"
    hindcast:
        field: 'OceanCurrents'
        source: 'hindcast_files'
        source_settings:
            local: False
            folder: "/tmp/hycom_hindcast/"
            source: "HYCOM"
            type: "hindcast"
    forecast:
        field: 'OceanCurrents'
        source: 'forecast_files'
        source_settings:
            local: False
            folder: "/tmp/hycom_forecast/"
            source: "HYCOM"
            type: "forecast"

solar_dict:
    hindcast: null
    forecast: null

seaweed_dict:
    hindcast: null
    forecast: null